name: "Build In Docker"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: '要使用的分支名称'
        required: true
        default: 'main'
      loglevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

env:
  LEVEL: ${{ inputs.logLevel }}
  TAGS: ${{ inputs.tags }}
  ENVIRONMENT: ${{ inputs.environment }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出指定分支的代码
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: 打印分支名称
        run: |
          echo "当前使用的 tag 是: ${{ github.event.inputs.tags }}"
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"

      - name: Debug Check workspace
        run: |
          pwd
          ls -al
          env
